=== vivek-gohil/OFSS-Mumbai-July-2024/XML/01_DTD/employee.dtd
<<<<<<< HEAD
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT employee (id,name,salary)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT salary (#PCDATA)>

=======
<!ELEMENT employee (id,name,salary,(phone|email),(address)*)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT address (block,street,city,pin)>
<!ELEMENT block (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT pin (#PCDATA)>
>>>>>>> 8fea0d0e9c9311295dc4faff410f8765cf83e461

=== vivek-gohil/OFSS-Mumbai-July-2024/XML/01_DTD/employee-external-dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employee SYSTEM "employee.dtd" >
<employee>
  <id>id</id>
  <name>name</name>
  <salary>salary</salary>
  <email>email</email>
  <address>
  	<block>A Block</block>
  	<street>F Street</street>
  	<city>Mumbai</city>
  	<pin>12345</pin>
  </address>
</employee>
